INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("The Box",SEC_TO_TIME(3002),8447,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Pura Pura Lupa",SEC_TO_TIME(2380),22037,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Secukupnya",SEC_TO_TIME(3668),12440,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Kraazy",SEC_TO_TIME(297),34838,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Tudo Ok",SEC_TO_TIME(187),25232,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Psycho",SEC_TO_TIME(1924),28447,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("All I Want - From 'High School Musical: The Musical: The Series'",SEC_TO_TIME(1549),24589,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("GOODMORNINGTOKYO!",SEC_TO_TIME(1355),49453,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("fine today (Nanti Kita Cerita Tentang Hari Ini - Original Motion Picture Soundtrack)",SEC_TO_TIME(611),2158,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Tusa",SEC_TO_TIME(3919),46790,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Break My Stride",SEC_TO_TIME(440),27989,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Say So",SEC_TO_TIME(2477),42844,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("SUGAR",SEC_TO_TIME(1688),20926,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Opaul",SEC_TO_TIME(2496),15970,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Vem Me Satisfazer",SEC_TO_TIME(865),30673,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Falling",SEC_TO_TIME(2110),27082,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Catriona",SEC_TO_TIME(405),20616,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Sigues Con El",SEC_TO_TIME(1019),37564,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Blinding Lights",SEC_TO_TIME(3720),49877,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Dolunay",SEC_TO_TIME(4608),46166,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Make It With You",SEC_TO_TIME(240),48290,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Suicidal",SEC_TO_TIME(4122),30168,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("German",SEC_TO_TIME(318),24213,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("No Idea",SEC_TO_TIME(3396),5122,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Sunday Best",SEC_TO_TIME(1340),8269,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("High Fashion (feat. Mustard)",SEC_TO_TIME(3452),26531,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Just the Way",SEC_TO_TIME(3963),16340,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Nobody But You (Duet with Gwen Stefani)",SEC_TO_TIME(4393),9714,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Bütün Istanbul Biliyo",SEC_TO_TIME(3659),36793,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Rumah Ke Rumah",SEC_TO_TIME(359),9292,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Rehat",SEC_TO_TIME(1439),13184,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Roses - Imanbek Remix",SEC_TO_TIME(2543),14101,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("OUT WEST (feat. Young Thug)",SEC_TO_TIME(825),48137,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Vibe With Me",SEC_TO_TIME(4813),15699,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Liberdade Provisória",SEC_TO_TIME(4684),25687,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("If the World Was Ending - feat. Julia Michaels",SEC_TO_TIME(3725),21064,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Wondering - From 'High School Musical: The Musical: The Series'",SEC_TO_TIME(3121),42859,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Dance Monkey",SEC_TO_TIME(1380),36641,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("ROXANNE",SEC_TO_TIME(3493),23758,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("FML",SEC_TO_TIME(1830),14656,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Ayy Macarena",SEC_TO_TIME(1186),19546,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Pelukku Untuk Pelikmu - OST Imperfect: Karier, Cinta, & Timbangan",SEC_TO_TIME(3961),24475,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Imahe",SEC_TO_TIME(3643),38065,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("I Want You Back",SEC_TO_TIME(1064),42333,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Texas Sun",SEC_TO_TIME(1290),17148,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("stupid",SEC_TO_TIME(1644),5330,1,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("I Love You but I'm Letting Go",SEC_TO_TIME(1651),44976,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Per due che come noi",SEC_TO_TIME(2721),6320,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Patointeligencja",SEC_TO_TIME(1236),39395,0,NULL);
INSERT INTO song(song_name, duration, price, is_sold, recommendation_id)VALUES("Lebih Dari Egoku",SEC_TO_TIME(3999),15837,0,NULL);


###users table

INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Zelda","Gage","Merrill","nec.luctus@Mauris.co.uk","ZTZ29FNJ5NL");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Eaton","Francis","Sargent","Nullam.feugiat.placerat@nec.net","OEW52XJF9KP");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Ezra","Gannon","Church","feugiat.nec@posuerecubiliaCurae.com","QMX20AFB4YA");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Lila","Isaac","Buchanan","Vivamus@Crasdolor.co.uk","YVI29CYC0ER");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Veda","Kasimir","Mcbride","tempor.lorem@fringilla.net","XZR40JSF0VE");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Lesley","Byron","York","laoreet@adipiscingelitEtiam.com","KEA58LUK9CF");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Tatiana","Stone","Soto","Ut.tincidunt@Aliquam.org","PUR25REI1PB");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Candice","Kieran","Ramirez","tempor@molestie.edu","UGC13RQF1HB");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Latifah","Tate","Albert","arcu@maurissitamet.net","KIX35UUY5RJ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Josiah","Brenden","Douglas","tortor@urnanec.co.uk","QVW23KAH0GE");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Xantha","Clayton","Donaldson","a.enim@semut.ca","PHM00UJF6CZ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Gannon","Chadwick","Palmer","nulla@at.co.uk","RPT19VKQ2MV");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Harding","Arden","Bennett","Duis.a.mi@Etiamlaoreet.ca","RDI75RHH8GZ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Macon","Barclay","Simpson","dignissim@porttitor.co.uk","RBT17KFJ7EN");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Brenden","Malik","Phelps","elit@nibhsitamet.com","CBS63ZTE1HC");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Azalia","George","Nixon","leo.Cras@Quisqueporttitor.edu","MQS86WNP2GK");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Castor","Bruno","Duran","eget.dictum@sitametrisus.org","RTI30PDG9AE");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Maya","Jason","Conner","risus.Donec@fermentumconvallisligula.edu","SXX53OPP1QS");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Octavia","Cruz","Marks","metus.Aenean.sed@eleifend.com","SAW21AKI3TT");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Ivory","Cade","Blackwell","volutpat@blandit.org","IDJ88CCH7DB");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Rhonda","James","Holder","mi.Duis@consectetueradipiscing.edu","AHG52NTJ2CW");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Gray","Gavin","Cardenas","nunc.est.mollis@liberonec.net","SRA34SXT2YR");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Raja","Leo","Johns","commodo@odio.com","OTR48PLJ6LE");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Calvin","Dalton","Romero","non@nuncullamcorpereu.com","OOY15HYQ3BW");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Jackson","Dalton","Conway","erat.volutpat.Nulla@nisi.net","LUQ63KAT8JS");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Zelenia","Kaseem","Griffith","Ut.tincidunt.vehicula@tellus.edu","LPT48ZZS3NU");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Baxter","Timothy","Pate","sed@posuereatvelit.com","URR02CDR1WQ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Maxwell","Geoffrey","Pate","convallis@Donec.org","YOZ58LCV2WU");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Ulysses","August","Chapman","diam.Sed@Phaselluslibero.co.uk","UBF69KTR1ZF");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Meredith","Ryder","Cabrera","nascetur@Crasvulputate.ca","PZM58YWI3ZM");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Cadman","Raymond","Marshall","Nulla.tincidunt@tincidunt.ca","HIB20NPI7JI");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Alyssa","Lewis","Duran","quam.elementum.at@Aliquamnisl.co.uk","XYT54LSD3TQ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Rebecca","Shad","Morin","Pellentesque.tincidunt.tempus@feugiatLoremipsum.org","UFG04FOI0IC");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Ignatius","Laith","Kinney","scelerisque.neque@semut.net","LNG61GOA6PB");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Arthur","Tucker","Dickson","risus@Nuncpulvinararcu.org","CDF37ETF7NQ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Noel","Eagan","Monroe","Integer.tincidunt@arcuVivamussit.com","SGB63UON5FB");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Charissa","Jasper","Flowers","sit.amet@ipsumcursus.edu","FQT10UXB6FW");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Nigel","Dustin","Kent","Phasellus.fermentum.convallis@ultriciesligulaNullam.edu","YXF86CEG0OZ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Myles","Uriah","Beard","dolor.vitae@felispurusac.net","TWV83OMF0NI");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Orla","Oren","Aguirre","parturient@etmalesuadafames.com","IIP93MKF2AP");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Moses","Magee","Thornton","Morbi.non.sapien@sitamet.ca","IQR32SSW5QH");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Mason","Hunter","Hebert","Proin.ultrices.Duis@Suspendissenonleo.org","MQS12EUT7MV");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Taylor","Kane","Joseph","ut.nulla.Cras@risusDonecegestas.com","UZZ22KOG7AJ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Mariam","Hakeem","Hayden","mauris.aliquam@nunc.edu","BRK62YQI2VY");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Troy","Jasper","Dorsey","dui.lectus@acliberonec.edu","IGD89JCH4GV");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Eaton","Malcolm","Bradshaw","luctus.sit.amet@magnaseddui.net","PTB57OZT7QG");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Liberty","Emmanuel","Michael","Mauris.quis.turpis@mauris.edu","JAK98QCD7JI");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Micah","Keaton","Huff","risus.Donec@eget.com","ULV65MYW9CX");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Jarrod","Justin","Parrish","mollis.non@rutrumnon.ca","VRD07SWW2JN");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Timon","Harding","Neal","arcu.iaculis@Nullamvitaediam.org","GNL42UDP5KK");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Carol","Wyatt","Giles","eu.erat.semper@Phasellusfermentum.net","NYZ86TOU4MQ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Fitzgerald","Caesar","Walter","pede.Praesent.eu@lacusEtiambibendum.edu","KKG21HEI6QM");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Kimberley","Steven","Figueroa","Integer@diamnuncullamcorper.co.uk","XHZ80CIW5ZA");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Cathleen","Paul","Pena","ut@aodio.com","QMI15ILN3UC");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Nell","Jin","Randall","tellus.faucibus.leo@quamelementum.net","TSX67YUP9MP");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Dana","Chadwick","Guy","fames.ac@egestasAliquamfringilla.ca","NDC53NWP3SC");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Nyssa","Elliott","Maynard","interdum.enim@auctorodioa.co.uk","KKC20CNP5KV");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Nita","Lars","Mayo","aliquam.iaculis@nec.org","DPP81MLL0IE");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Justina","Orlando","Webster","est@enimSed.net","JSI55NNN0BS");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Sharon","Ivan","Farmer","elit@Quisque.edu","BKC88IFU6UL");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Tanya","Gavin","Keller","neque.Morbi.quis@felisDonec.net","TLZ45JFC8UC");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Isabella","Steven","Gonzalez","lacus@vulputatedui.net","QAZ21JYF8IC");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Orson","Judah","Church","mi.eleifend@lectusCum.ca","VZA77HYC4VH");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Blair","Malachi","Mccoy","scelerisque.neque.sed@convallis.org","FIN24OJY3XY");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Noelani","Knox","Goodman","ultricies.adipiscing@pedeSuspendissedui.net","HGF52DFO6RG");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Kelly","Timon","Weeks","tristique.senectus.et@aenim.com","BQS73MPD6RJ");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Blaze","Thor","Pacheco","arcu.Vestibulum.ante@porttitorinterdum.ca","KKB45PWI8DG");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Rajah","Valentine","Shaw","et@euarcuMorbi.org","TXM39SMD2BX");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Aspen","Kyle","Pate","Nullam@aliquetPhasellusfermentum.org","FZY44CTU1BV");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Wilma","Wesley","Combs","vitae.aliquet.nec@velarcu.org","FRD22VTQ9BO");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Sasha","Jelani","Hawkins","non@ipsumdolorsit.co.uk","MVC85EKZ6HB");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Bell","Hall","English","placerat.orci@augue.com","UIU78ZLW7IU");
INSERT INTO `user` (`user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES ("Hiroko","Christian","Bass","neque.In.ornare@urnaVivamusmolestie.net","IML67AZK1HP");

##admin user
INSERT INTO `user` (`user_id`, `user_name`,`name`,`last_name`,`e_mail`,`password`) VALUES (99, "admin","Münevver","Kocatürk","munevverkocaturk@std.sehir.edu.tr","12345");


##COMPOSER
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  1  ,  29236280610  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  2  ,  75484311399  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  3  ,  23605317619  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  4  ,  38032968774  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  5  ,  54125193914  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  6  ,  23836867534  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  7  ,  76033884341  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  8  ,  37277649595  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  9  ,  73101169563  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  10  ,  66084811786  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  11  ,  30469026446  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  12  ,  22975684492  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  13  ,  20074487795  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  14  ,  45738636331  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  15  ,  65696947399  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  16  ,  30032078464  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  17  ,  84403827460  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  18  ,  18284720470  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  19  ,  48154938939  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  20  ,  29887025259  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  21  ,  37442463640  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  22  ,  65993195571  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  23  ,  76861423358  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  24  ,  50940402947  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  25  ,  44664319503  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  26  ,  40710113955  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  27  ,  15818000485  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  28  ,  41088795380  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  29  ,  17760920411  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  30  ,  43311863292  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  31  ,  13988129862  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  32  ,  77955385497  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  33  ,  20514376157  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  34  ,  37955884719  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  35  ,  46280963479  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  36  ,  34484670044  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  37  ,  20306093138  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  38  ,  35554951798  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  39  ,  22147002637  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  40  ,  71778884244  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  41  ,  30056644410  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  42  ,  61634065807  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  43  ,  19526718071  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  44  ,  12081811959  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  45  ,  54407359689  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  46  ,  24542571001  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  47  ,  60483279297  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  48  ,  11106339057  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  49  ,  73216628716  )  ;
INSERT INTO composer  (user_id, national_id_number)  VALUES  (  50  ,  13252431171  )  ;




##perform

INSERT INTO perform  (song_id, composer_id)  VALUES  (  1  ,  1  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  2  ,  2  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  3  ,  3  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  4  ,  4  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  5  ,  5  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  6  ,  6  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  7  ,  7  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  8  ,  8  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  9  ,  9  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  10  ,  10  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  11  ,  11  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  12  ,  12  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  13  ,  13  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  14  ,  14  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  15  ,  15  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  16  ,  16  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  17  ,  17  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  18  ,  18  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  19  ,  19  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  20  ,  20  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  21  ,  21  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  22  ,  22  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  23  ,  23  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  24  ,  24  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  25  ,  25  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  26  ,  26  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  27  ,  27  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  28  ,  28  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  29  ,  29  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  30  ,  30  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  31  ,  31  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  32  ,  32  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  33  ,  33  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  34  ,  34  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  35  ,  35  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  36  ,  36  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  37  ,  37  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  38  ,  38  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  39  ,  39  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  40  ,  40  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  41  ,  41  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  42  ,  42  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  43  ,  43  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  44  ,  44  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  45  ,  45  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  46  ,  46  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  47  ,  47  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  48  ,  48  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  49  ,  49  )  ;
INSERT INTO perform  (song_id, composer_id)  VALUES  (  50  ,  50  )  ;



##Customer
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  51  ,  27503216881  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  52  ,  47425292407  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  53  ,  89193825252  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  54  ,  40371310656  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  55  ,  72994994303  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  56  ,  46046026602  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  57  ,  41599966399  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  58  ,  21397176215  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  59  ,  51418322180  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  60  ,  46398273299  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  61  ,  35847824906  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  62  ,  85007581674  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  63  ,  71490433198  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  64  ,  21852836209  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  65  ,  62558308762  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  66  ,  49036432769  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  67  ,  38903748650  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  68  ,  42712521892  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  69  ,  12782398908  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  70  ,  60929721137  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  71  ,  64757595157  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  72  ,  21518057068  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  73  ,  14166190536  )  ;
INSERT INTO customer  (user_id, national_id_number)  VALUES  (  99  ,  14145679885  )  ;

###genre_film
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  1  ,  "Action"  )  ;
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  2  ,  "Comedy"  )  ;
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  3  ,  "Drama")  ;
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  4  ,  "Fantasy"  )  ;
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  5  ,  "Horror"  )  ;
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  6  ,  "Mystery"  )  ;
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  7  ,  "Romance"  )  ;
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  8  ,  "Thriller"  )  ;
INSERT INTO genre_film  (genre_id, genre_type)  VALUES  (  9  ,  "Western"  )  ;

##instrument_category
INSERT INTO 	instrument_category	(instrument_id,instrument_category)	VALUES	(	1	,	"bowed strings"	)	;
INSERT INTO 	instrument_category	(instrument_id,instrument_category)	VALUES	(	2	,	"woodwind"	)	;
INSERT INTO 	instrument_category	(instrument_id,instrument_category)	VALUES	(	3	,	 "brass"	)	;
INSERT INTO 	instrument_category	(instrument_id,instrument_category)	VALUES	(	4	,	"percussion"	)	;
INSERT INTO 	instrument_category	(instrument_id,instrument_category)	VALUES	(	5	,	"keyboard"	)	;
INSERT INTO 	instrument_category	(instrument_id,instrument_category)	VALUES	(	6	,	"the guitar family"	)	;

###Recommendation data
INSERT INTO 	recommendation	(recommendation_id, video_file, offer_price, customer_id)	VALUES	(	1	,	"mov1.mp4",	8169	,	55	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	2	,	"mov2.mp4",	4309	,	71	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	3	,	"mov3.mp4",	8964	,	62	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	4	,	"mov4.mp4",	9106	,	55	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	5	,	"mov5.mp4",	390	,	67	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	6	,	"mov6.mp4",	4349	,	67	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	7	,	"mov7.mp4",	6600	,	73	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	8	,	"mov8.mp4",	7243	,	58	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	9	,	"mov9.mp4",	4064	,	65	)	;
INSERT INTO 	recommendation	(recommendation_id,video_file,offer_price,customer_id)	VALUES	(	10	,	"mov10.mp4",	7369	,	69	)	;


 ##song_genre 
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	1	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	6	,	2	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	2	,	3	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	5	,	4	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	5	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	8	,	6	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	7	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	1	,	8	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	8	,	9	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	4	,	10	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	1	,	11	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	9	,	12	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	4	,	13	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	5	,	14	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	9	,	15	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	9	,	16	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	5	,	17	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	7	,	18	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	6	,	19	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	2	,	20	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	4	,	21	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	8	,	22	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	5	,	23	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	7	,	24	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	8	,	25	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	26	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	27	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	6	,	28	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	4	,	29	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	8	,	30	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	8	,	31	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	7	,	32	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	9	,	33	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	6	,	34	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	35	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	36	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	5	,	37	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	38	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	7	,	39	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	4	,	40	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	1	,	41	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	3	,	42	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	4	,	43	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	1	,	44	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	4	,	45	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	8	,	46	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	1	,	47	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	4	,	48	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	6	,	49	)	;
INSERT INTO 	song_genre	(genre_id, song_id)	VALUES	(	9	,	50	)	;


###song_inst_cat
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	1	,	1	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	2	,	5	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	3	,	6	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	4	,	1	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	5	,	5	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	6	,	6	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	7	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	8	,	4	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	9	,	1	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	10	,	6	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	11	,	2	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	12	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	13	,	4	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	14	,	6	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	15	,	5	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	16	,	6	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	17	,	4	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	18	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	19	,	6	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	20	,	4	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	21	,	6	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	22	,	5	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	23	,	5	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	24	,	5	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	25	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	26	,	2	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	27	,	2	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	28	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	29	,	2	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	30	,	4	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	31	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	32	,	1	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	33	,	1	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	34	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	35	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	36	,	1	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	37	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	38	,	5	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	39	,	4	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	40	,	6	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	41	,	2	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	42	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	43	,	4	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	44	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	45	,	1	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	46	,	3	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	47	,	2	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	48	,	2	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	49	,	4	)	;
INSERT INTO 	song_inst_cat	(song_id, instrument_id)	VALUES	(	50	,	4	)	;
